name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t dockerhub-hajargouchgache/first-image .
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.hajargouchgache}} -p ${{
            secrets.Cloudlink.2023 }}
    - name: Push Docker image to Docker Hub
      run: docker push dockerhub-hajargouchgache/first-image

